// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajxbjxoujummahqcctuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqeGJqeG91anVtbWFocWNjdHVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTI4NTYsImV4cCI6MjA2NzU4ODg1Nn0.AO8Ylfjf7bWoGtA1fVZCniQS7vl2IjwHvIjIMQG4f2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});